steps:
- name: 'python:3.7'                                                                                                                               
  entrypoint: python3                                                               
  args: ['-m', 'pip', 'install', '-t', '.', '-r', 'requirements.txt'] 
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$_BUCKET/app.yaml', 'html/app.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','app', 'deploy', '--no-cache','html/']