# Generated by Django 3.0.7 on 2020-06-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('user_id', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
