# Generated by Django 3.0.7 on 2020-06-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardholder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardholder',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
