# Generated by Django 3.0.7 on 2020-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardholder', '0002_auto_20200617_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('private_key', models.CharField(max_length=1024)),
                ('public_key', models.CharField(max_length=256)),
            ],
        ),
    ]
