# Generated by Django 3.0.7 on 2020-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardholder', '0003_platformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='private_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='platformmodel',
            name='public_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
