# Generated by Django 3.0.7 on 2020-06-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardholder', '0005_customermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='e_commerce_id',
            new_name='e_commerce',
        ),
    ]
