# Generated by Django 3.0.7 on 2020-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardholder', '0007_auto_20200619_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=255, unique=True)),
                ('public_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
