# Generated by Django 3.0.7 on 2020-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardholder', '0009_auto_20200619_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardholdermodel',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
