# Generated by Django 3.0.7 on 2020-06-22 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardholder', '0010_auto_20200619_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardholdermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
